[package]
name = "diesel_streamer_tests"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = { version = "0.4" }
diesel = { version = "2", features = ["postgres", "chrono"]}
diesel-streamer = { path = "../diesel-streamer" }
dotenvy = "0.15"
